name: hand_car
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  animated_list_item: ^1.0.0
  carousel_slider: ^5.0.0
  
  concentric_transition: ^1.0.3
  dio: ^5.7.0
  fan_carousel_image_slider: ^1.0.1
  flutter:
    sdk: flutter
  flutter_gen: ^5.7.0
  flutter_hooks: ^0.20.5
  flutter_onboarding_slider: ^1.0.11
  flutter_otp_text_field: ^1.2.0
  flutter_rating_bar: ^4.0.1
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  image_picker: ^1.1.2
  json_to_dart: ^1.0.5
  lottie: ^3.1.2
  rating_summary: ^1.0.3+1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13
  flutter_launcher_icons: ^0.14.1
  


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/hand_car_logo.png"
  adaptive_icon_background: "#FFFFFF"  # Example: Use a plain color or specify another image
  adaptive_icon_foreground: "assets/icons/hand_car_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
        